### PR TITLE
Fix race conditions caused by queued signal/slot connections

### LINKED ISSUE #39: Race condition in "object_set_properties"
The command "object_set_properties" uses a queued signal/slot connection for its execution, so the TCP response may be sent before the property was actually set. If the command "object_properties" follows immediately, it could return the *old* property values instead of the new ones!

https://github.com/parkouss/funq/blob/f125890ab01a102063ecfa383504f2082560bd6a/server/libFunq/player.cpp#L249-L251

I noticed that because the functional test `test_retrieve_widget.py:TestRetrieve.test_widget_set_properties` fails sporadically.

So we must make sure that the response is always sent *after* the properties are set.

### PR DESCRIPTION
**Pull request by ubruhin**
I'm not completely sure if it has any disadvantage to replace the queued connections by direct connections, but at least the tests seem to be stable now ;)

Fixes #39.

Note: This conflicts with #54 - if one PR is merged, I'll rebase the other one.

### CODE REVIEW

**Comment by ubruhin** [comment]
Rebased to master, as #54 is now merged (thanks for merging! :smiley: ).

**Comment by parkouss** [comment]
Hm, sadly I can't remember why this code was like this... I guess we can start applying your change, and in case anything goes wrong later we can still roll back the operation. (adding a test that would break at the same time if possible so we won't do the same mistake twice)

**Comment by ubruhin** [comment]
> I guess we can start applying your change, and in case anything goes wrong later we can still roll back the operation. (adding a test that would break at the same time if possible so we won't do the same mistake twice)

Sounds reasonable :+1:

Hmm now another test has failed, but I suspect it has nothing to do with this change...I'll take a look at it.

```
======================================================================
FAIL: test_click.py:TestClick.test_middle_click
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\funq\tests-functionnal\test_click.py", line 56, in test_middle_click
    self.assertEquals(self.get_status_text(), 'middle clicked !')
AssertionError: u'' != 'middle clicked !'
-------------------- >> begin captured logging << --------------------
funq.client: INFO: The tested application will be launched in the directory 'C:\\projects\\funq\\tests-functionnal\\.' with the command ['C:\\Python27\\Scripts\\funq.exe', '--port', '1053', 'C:\\projects\\funq\\tests-functionnal\\./funq-test-app/funq-test-app']
funq.client: INFO: Launching tested application [3024].
--------------------- >> end captured logging << ---------------------
```

**Comment by parkouss** [comment]
Hey @ubruhin ,

Thanks a lot first for investigation and explanations. :)

I am not convinced either that adding a blocking= argument is a good solution for the issue. I would prefer that each action on the server detect the end of it, and use a DelayedResponse to send back the answer when it is ready.

For clicking, I am not sure, maybe using implementation of Qttest (if it is synchronous?, which I don't know) would solve the issue? Or maybe using something like an EventWaiter (example https://forum.qt.io/topic/70018/wait-on-event/3) to wait for the mouse click to be processed before sending a response?

**Comment by ubruhin** [comment]
I'm not sure if you understood me correctly ;) The function `qApp->notify()` *is* synchronous, so it returns only if the event is fully processed. Thus the race conditions are fixed. (Btw, I just noticed that `qApp->sendEvent()` is probably better than `qApp->notify()`, see [here](https://forum.qt.io/topic/18047/qevent-and-notify))

So, one could think to just always use `qApp->sendEvent()` instead of `qApp->postEvent()`, and everything is fine. But that's not the case, there are still two different issues:

### Issue 1

If the receiver of the event (i.e. the application under test, AUT) does something blocking, the function `qApp->sendEvent()` doesn't return until the blocking action has finished. Consider following code in a class of the AUT:

```
void mouseDoubleClickEvent(QMouseEvent * e) {
    if (QMessageBox::question(this, "Question", "Are you sure?") == QMessageBox::Yes) {
        doSomething();
    }
}
```

The method `QMessageBox::question()` is blocking the main event loop, thus the double click event (sent from libFunq) is not fully processed until the message box is clicked away, meaning that `qApp->sendEvent()` never returns. I think also the DelayedResponse, QtTest functions or an EventWaiter can't fix this issue.

Basically only the user (i.e. developer of the AUT) knows whether an event will trigger a blocking action or not, thus I added the "blocking" parameter which the user can set to False to avoid this issue.

But maybe there would be a more sophisticated solution. The `QMessageBox` (or any other modal `QDialog`) basically only blocks event processing in the *main* event loop - but they start a new, nested event loop to continue event processing. Maybe libFunq could somehow send the actual event with `qApp->postEvent()` (non-blocking), and a "dummy event" afterwards also with `qApp->postEvent()`. If we use the second event to send the TCP response to the Funq client, we can (hopefully) be sure that the first event was either fully processed too (if it was non-blocking) or it opened a nested event loop (if it was blocking). In both cases, the event can be considered as "processed" and we can send the TCP response. No idea if that works, but I'll give it a try :)

### Issue 2

Another issue is that in the AUT, an event might be processed asynchronously. Consider following code in the AUT:

```
void mouseDoubleClickEvent(QMouseEvent * e) {
    QTimer::singleShot(100, this, SLOT(doSomething()));
}
```

The event itself is processed immediately (i.e. `qApp->sendEvent()` returns immediately), but the actual action (`doSomething()`) is delayed by 100ms. And there is no chance for libFunq to detect the end of the action, as it's very application specific. Thus I think this kind of issue must be solved by the user anyway (by waiting until the action has completed).

A special case are events which by themselves add more events to the event queue, for example queued signal/slot connections, or calls to `QTimer::singleShot()` with 0ms delay (which is sometimes used to "asynchronously" execute a function). It would be nice to also have these events fully processed before libFunq sends the TCP response. Maybe this could also be done with the idea of a "dummy event" from above.

**Comment by parkouss** [comment]
Right, the idea of using qttest might not work. I think I originally understood you well though, but now that I read myself again the EventWaiter name was really a bad name. Let me explain that once more, I think it covers the first point above.

The idea is to use postEvent. Always, to never block any event loop. One or more event can be send this way, and we can listen to when there are processed by creating an event filter and installing it on the target widget (well I suppose that when returning from filterEvent the event has been processed directly). Once the last interesting event has been seen, we could then fire back the DelayedResponse (in a qtimer::singleShot with 0ms delay).

With this approach, we never block, but we answer once the events have been processed. Obviously we don't handle the above point 2 - but I believe this one might only be fixed by some knowledge of the application under testing, and with specific api used on the client side (I suppose).

Does that make more sense now? What you mention with the dummy event might be be clever though, and I see it as quite the same idea (wait for events being processed - in a non blocking way, and send back the response). I believe the dummy event can be sent to the target object - as the last event, and using an event filter used to send back the response (being probalby some std::function now that c++ 11 is quite popular).

**Comment by ubruhin** [comment]
Ah I see, yeah that makes more sense :)

I worked a bit on that, and I tried to write a test which fails with the current implementation to be sure we never accidentally revert this fix in future. But unfortunately I didn't find a way to reproduce the race conditions :( I also retriggered the Travis/AppVeyor builds several times, and they were all successful.

Even more, I'm no longer really sure that race conditions were the reason for the random failures - it's true that the TCP response is sent back to the client *before* the event is processed. But actually this is not an issue as long as the event is executed before the next TCP packet from the client is received, and that's extremely unlikely (if not impossible). Or how can a received TCP packet be processed *before* processing the events which were already in the event queue before the TCP packet arrived?

I'm very confused now - I added delays to the tests of my application some time ago because I experienced such race conditions. But I can no longer reproduce them, and don't understand exactly how such race conditions can happen. :thinking:

**Comment by parkouss** [comment]
The command stress might help to reproduce issues that appear randomly, due to cpu usage or things like this if you don't know about it. E.g, running `stress -c 16 --timeout 60` in one shell while running the tests.

Other than that, I have no idea for now - I don't understand either :(.

**Comment by ubruhin** [comment]
Ah, good idea :+1: I'll try it some time, but if I can't reproduce it, we can probably close this PR ;)

**Comment by rafaeldelucena** [comment]
Thanks for the explanation, as you said in the issue 2, the scenario depends of an implementation detail from the AUT, so the developer has be aware of this. Maybe someday we can implement a way to check for timers or even which events are triggered.

For the implementation:

 - Because of the breaking change, I think a good approach will be update the funq version using [Semantic Versioning](https://semver.org/spec/v2.0.0.html), since funq is used by other projects and we must ensure that we cannot break any tests of our users.

 - Also will be awesome if you add an entry on the CHANGELOG.md using [this pattern](https://keepachangelog.com/en/1.0.0/), to keep the history of the changes and improvements in the project.

**Comment by ubruhin** [comment]
Sounds reasonable :+1:

For the moment, I added "WIP" to the PR title as this is not ready to merge yet.

And for the record, here are two failed tests on Windows which I suspect to be related to these "mystery race conditions":

https://ci.appveyor.com/project/parkouss/funq/builds/21360912:

```
======================================================================
FAIL: test_click.py:TestClick.test_click_header_R1_by_name
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\projects\funq\client\funq\testcase.py", line 190, in wrapper
    return func(self, *args, **kwargs)
  File "C:\projects\funq\tests-functionnal\test_click.py", line 79, in test_click_header
    self.assertEquals(self.get_status_text(), orientation + " Header clicked: " + str(result_index))
AssertionError: u'' != 'H Header clicked: 0'
-------------------- >> begin captured logging << --------------------
funq.client: INFO: The tested application will be launched in the directory 'C:\\projects\\funq\\tests-functionnal\\.' with the command ['C:\\Python27\\Scripts\\funq.exe', '--port', '1052', 'C:\\projects\\funq\\tests-functionnal\\./funq-test-app/funq-test-app']
funq.client: INFO: Launching tested application [2740].
--------------------- >> end captured logging << ---------------------
======================================================================
FAIL: test_click.py:TestClick.test_key_click_sometext
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\projects\funq\client\funq\testcase.py", line 190, in wrapper
    return func(self, *args, **kwargs)
  File "C:\projects\funq\tests-functionnal\test_click.py", line 70, in test_key_click
    self.assertEquals(self.get_status_text(), text)
AssertionError: u'' != 'Hello this is me !'
-------------------- >> begin captured logging << --------------------
funq.client: INFO: The tested application will be launched in the directory 'C:\\projects\\funq\\tests-functionnal\\.' with the command ['C:\\Python27\\Scripts\\funq.exe', '--port', '1052', 'C:\\projects\\funq\\tests-functionnal\\./funq-test-app/funq-test-app']
funq.client: INFO: Launching tested application [2532].
--------------------- >> end captured logging << ---------------------
----------------------------------------------------------------------
```

Proof that these are random: Following AppVeyor build has tested the exactly same code base (see commit hash), but was successful: https://ci.appveyor.com/project/ubruhin/funq/builds/21361526

**Comment by ubruhin** [comment]
Unfortunately using `stress` did not help to reliable reproduce this issue. I really have troubles in reproduce it locally, it happens very rarely on my machine. But on AppVeyor it happens pretty often, so I put some debug output in `libFunq` and `funq-test-app` to see what's going on :wink: And voila, there it is! :smiley: 

"Function trace" of the test "test_click.py:TestClick.test_double_click":

```
0 - Debug: =======================================================
1010 - Debug: funq is initialized on host  "127.0.0.1"  and on port  1042 .
1477 - Debug: [libFunq] Command received: "widget_by_path"
1477 - Debug: [libFunq] Response sent
1477 - Debug: [libFunq] Command received: "object_properties"
1477 - Debug: [libFunq] Response sent
1477 - Debug: [libFunq] Command received: "object_properties"
1477 - Debug: [libFunq] Response sent
1477 - Debug: [libFunq] Command received: "widget_click"
1477 - Debug: [libFunq] mouse_click()
1477 - Debug: [libFunq] Response sent
1477 - Debug: [libFunq] Command received: "widget_by_path"
1477 - Debug: [libFunq] Response sent
1477 - Debug: [libFunq] Command received: "object_properties"
1477 - Debug: [libFunq] Response sent
1477 - Debug: [libFunq] Command received: "object_properties"
1477 - Debug: [libFunq] Response sent
1477 - Debug: [libFunq] Command received: "widget_click"
1477 - Debug: [libFunq] mouse_dclick()
1477 - Debug: [libFunq] mouse_click()
1477 - Debug: [libFunq] Response sent
1477 - Debug: [libFunq] Command received: "widget_by_path"
1477 - Debug: [libFunq] Response sent
1477 - Debug: [libFunq] Command received: "object_properties"
1477 - Debug: [libFunq] Response sent
1477 - Debug: [libFunq] Command received: "object_properties"
1477 - Debug: [libFunq] Response sent
1477 - Debug: [libFunq] Command received: "grab"
1477 - Warning: this function is deprecated, use QScreen::grabWindow() instead. Defaulting to primary screen.
1840 - Debug: [libFunq] Response sent
1840 - Debug: [app] DoubleClickDialog::mouseDoubleClickEvent()
1840 - Debug: [app] SimpleDialog::showResult(): "double clicked !"
1934 - Debug: [libFunq] Command received: "quit"
1934 - Debug: [libFunq] Response sent
```

It's clearly visible that between the "widget_click" command and its corresponding slot `mouseDoubleClickEvent()` in the AUT there are even **four**(!) other commands executed by funq! So, somehow the click event takes very long until it's really processed. But I still don't know why, and don't know how to reproduce it reliable...

Notes:
- The number is time in milliseconds since application start.
- The "grab" command is automatically performed by the test framework because the test failed.

**Comment by ubruhin** [comment]
As this is a really weird thing and I currently don't have the time to fix the race conditions properly, I decided to revert this PR to its original purpose: just removing the queued signal/slot connection by a direct function call. This fixes at least the race conditions of the `object_properties` and `object_set_properties` commands, so it's at least a small improvement. I hope you agree with that ;)

Maybe I can also fix the other race condition issues some day, but it seems to require a lot of time, so I can't guarantee it.

Sorry for the circumstances :wink:

**Comment by rafaeldelucena** [comment]
Ok, thank you for the efforts!

**Pull request merged**
