### PR TITLE
Add support for right/middle click

### LINKED ISSUE #46: Right click support
Hi, thanks for your library!

Is there a way to get right click support in funq right now? It seems that it's not yet implemented, is that correct?

(I can simulate the right click using click + menu button, but that's not dispatching the same Qt events...)

### PR DESCRIPTION
**Pull request by dbrgn**
This fixes #46.

In the server, I made the click function parametrized, so that any mouse button could be used.

Right now, besides the "click" action that already existed, only "rightclick" is exposed. This could be extended later on with a parametrized action (although middle click is probably the only other click action that people might want).

Unfortunately I don't know how to try it out, but at least "python setup.py develop" in the server directory worked.

### CODE REVIEW

**Comment by rafaeldelucena** [comment]
Thanks for the contribution!

I already make a fix #50 into the docs to make the build system run green again =D

The code seems good, could you can write a functional test for this feature? I can help you with that if you have some trouble.

Best

**Comment by rafaeldelucena** [comment]
Ok, first you have to create a `RighClickDialog` simliar to `ClickDialog` inside `tests-functionnal/funq-test-app/widgets.h`, but with `rightClicked` signal.


After that you can add a new test in `tests-functionnal/test_click.py` like the others but using your new dialog

**Comment by rafaeldelucena** [comment]
Almost forgot, you have to add the dialog into `tests-functionnal/funq-test-app/main.cpp` also =)

**Comment by dbrgn** [comment]
Tests added! :slightly_smiling_face: 

By the way, you have a typo in the directory name: "functionnal" should be "functional".

**Comment by dbrgn** [comment]
Before merging: Since I also need middle click support soon, I think it makes more sense to parametrize the `click` function instead of adding both a `rclick` and `mclick` method.

**Comment by rafaeldelucena** [comment]
> I think it makes more sense to parametrize the `click` function instead of adding both a `rclick` and `mclick` method.

It's a good idea =)

> I'll update the PR accordingly.

You can leave in this way until needs the changes at middle click PR =)

**Comment by dbrgn** [comment]
Done :tada:

**Comment by rafaeldelucena** [comment]
Hmmm there is a small style issue:

```
client/funq/models.py:290:80: E501 line too long (82 > 79 characters)
```

**Comment by dbrgn** [comment]
Ah. I've set my line length limiter to 99, that's why I didn't notice :slightly_smiling_face: 

Fixed.

**Pull request merged**
